### ISSUE TITLE
对于行人数据集是否可以生成较好的文本描述？

### ISSUE THREAD

**Issue by shams2023** [NohTow/WTF-RL#1]

**Comment by NohTow** [comment]
I am not sure to understand, would you mind asking in English please?

**Comment by shams2023** [comment]
> I am not sure to understand, would you mind asking in English please?

Can better text descriptions be generated for pedestrian datasets?

**Comment by NohTow** [comment]
Well, if your dual encoder (the CLIP model) has information about pedestrian data (i.e, can correctly retrieve specific pedestrian images among others), then yes, but I do not know if CLIP itself is good at this.
